import type { SkillDefinition } from "./skillTypes";

export const SAMPLE_SKILLS: SkillDefinition[] = [
  {
    id: "skill-web-search",
    name: "Web Search",
    slug: "web_search",
    version: "1.2.0",
    description: "Search the web and return structured results. Supports query filters, date ranges, and source restrictions.",
    category: "Research",
    tags: ["search", "web", "research"],
    source: "built-in",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw", "claude", "codex"],
    inputSchema: {
      query: { type: "string", required: true },
      maxResults: { type: "number", default: 10 },
      dateRange: { type: "string", enum: ["any", "day", "week", "month", "year"] },
    },
    outputSchema: {
      results: { type: "array" },
      summary: { type: "string" },
    },
    instructions: "Use this skill to retrieve real-time web search results. Always pass a focused query string. Use dateRange to narrow results for recent events.",
    examples: [
      {
        title: "Basic search",
        input: '{ "query": "latest AI research papers 2025" }',
        output: '{ "results": [...], "summary": "Found 10 results about AI research..." }',
      },
    ],
    metadata: { createdAt: "2024-11-01", notes: "Built-in skill, always available." },
  },
  {
    id: "skill-report-generation",
    name: "Report Generation",
    slug: "report_generation",
    version: "1.0.0",
    description: "Generate structured reports from research data, summaries, or raw content. Supports multiple output formats.",
    category: "Synthesis",
    tags: ["report", "synthesis", "document", "output"],
    source: "built-in",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw", "claude"],
    inputSchema: {
      content: { type: "string", required: true },
      format: { type: "string", enum: ["markdown", "html", "json"], default: "markdown" },
      tone: { type: "string", enum: ["executive", "technical", "casual"], default: "executive" },
    },
    outputSchema: {
      report: { type: "string" },
      wordCount: { type: "number" },
    },
    instructions: "Pass raw data or bullet-point notes as `content`. Specify the desired format and tone. The skill structures the content into a coherent report.",
    metadata: { createdAt: "2024-12-01" },
  },
  {
    id: "skill-code-review",
    name: "Code Review",
    slug: "code_review",
    version: "0.9.1",
    description: "Analyse source code for bugs, style issues, and security vulnerabilities. Returns structured findings.",
    category: "Engineering",
    tags: ["code", "review", "analysis", "security"],
    source: "workspace",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw", "codex"],
    inputSchema: {
      code: { type: "string", required: true },
      language: { type: "string", required: true },
      focus: { type: "array", items: { type: "string", enum: ["bugs", "style", "security", "performance"] } },
    },
    outputSchema: {
      findings: { type: "array" },
      severity: { type: "string", enum: ["low", "medium", "high", "critical"] },
    },
    metadata: { createdAt: "2024-12-10" },
  },
  {
    id: "skill-doc-summary",
    name: "Document Summary",
    slug: "doc_summary",
    version: "1.0.0",
    description: "Summarise long-form documents into structured bullet points or executive summaries.",
    category: "Research",
    tags: ["summary", "document", "extract"],
    source: "built-in",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw", "claude"],
    inputSchema: {
      document: { type: "string", required: true },
      maxLength: { type: "number", default: 500 },
      style: { type: "string", enum: ["bullets", "paragraph", "tldr"], default: "bullets" },
    },
    outputSchema: {
      summary: { type: "string" },
    },
    metadata: { createdAt: "2025-01-05" },
  },
];
