import type { ToolDefinition } from "./toolTypes";

export const SAMPLE_TOOLS: ToolDefinition[] = [
  {
    id: "tool-browser",
    name: "Browser",
    slug: "browser",
    version: "2.0.0",
    description: "Control a headless browser to navigate pages, fill forms, click elements, and extract structured content.",
    category: "Web",
    tags: ["browser", "web", "automation", "navigation"],
    source: "built-in",
    executionType: "provider",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw"],
    inputSchema: {
      url: { type: "string", required: true },
      actions: { type: "array", items: { type: "object" } },
      waitFor: { type: "string" },
    },
    outputSchema: {
      html: { type: "string" },
      text: { type: "string" },
      screenshot: { type: "string", format: "base64" },
    },
    metadata: { createdAt: "2024-11-01", notes: "Requires OpenClaw provider with browser capability." },
  },
  {
    id: "tool-screenshot",
    name: "Screenshot",
    slug: "screenshot",
    version: "1.1.0",
    description: "Capture screenshots of web pages or specific DOM elements. Returns base64-encoded image data.",
    category: "Web",
    tags: ["screenshot", "capture", "visual", "image"],
    source: "built-in",
    executionType: "provider",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw"],
    inputSchema: {
      url: { type: "string", required: true },
      selector: { type: "string" },
      fullPage: { type: "boolean", default: false },
      width: { type: "number", default: 1280 },
      height: { type: "number", default: 800 },
    },
    outputSchema: {
      image: { type: "string", format: "base64" },
      mimeType: { type: "string" },
    },
    metadata: { createdAt: "2024-11-15" },
  },
  {
    id: "tool-file-io",
    name: "File I/O",
    slug: "file_io",
    version: "1.0.0",
    description: "Read and write files from the workspace filesystem. Supports streaming reads for large files.",
    category: "Filesystem",
    tags: ["file", "io", "filesystem", "read", "write"],
    source: "built-in",
    executionType: "local",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw", "codex"],
    inputSchema: {
      operation: { type: "string", enum: ["read", "write", "append", "delete", "list"], required: true },
      path: { type: "string", required: true },
      content: { type: "string" },
      encoding: { type: "string", default: "utf-8" },
    },
    outputSchema: {
      content: { type: "string" },
      size: { type: "number" },
      success: { type: "boolean" },
    },
    metadata: { createdAt: "2024-11-01" },
  },
  {
    id: "tool-http-request",
    name: "HTTP Request",
    slug: "http_request",
    version: "2.1.0",
    description: "Make GET, POST, PUT, DELETE requests to external APIs with configurable headers, timeout, and auth.",
    category: "Network",
    tags: ["http", "api", "network", "rest"],
    source: "built-in",
    executionType: "api",
    status: "active",
    visibility: "workspace",
    providerCompatibility: ["openclaw", "codex", "claude"],
    inputSchema: {
      method: { type: "string", enum: ["GET", "POST", "PUT", "PATCH", "DELETE"], required: true },
      url: { type: "string", required: true },
      headers: { type: "object" },
      body: { type: "string" },
      timeoutMs: { type: "number", default: 10000 },
    },
    outputSchema: {
      status: { type: "number" },
      headers: { type: "object" },
      body: { type: "string" },
    },
    metadata: { createdAt: "2024-12-01" },
  },
  {
    id: "tool-code-exec",
    name: "Code Executor",
    slug: "code_exec",
    version: "0.8.2",
    description: "Execute sandboxed code snippets in Python, JS, or Bash and return stdout/stderr.",
    category: "Engineering",
    tags: ["code", "execute", "sandbox", "python", "bash"],
    source: "built-in",
    executionType: "local",
    status: "draft",
    visibility: "workspace",
    providerCompatibility: ["openclaw", "codex"],
    inputSchema: {
      language: { type: "string", enum: ["python", "javascript", "bash"], required: true },
      code: { type: "string", required: true },
      timeoutSec: { type: "number", default: 30 },
    },
    outputSchema: {
      stdout: { type: "string" },
      stderr: { type: "string" },
      exitCode: { type: "number" },
    },
    metadata: { createdAt: "2025-01-15", notes: "Draft — sandbox environment not yet fully configured." },
  },
];
